name:                Glados-On-Top
version:             2.0.0
github:              "vincbct34/Glados-On-Top"
license:             BSD-3-Clause
author:              "Let us cook once more"
maintainer:          "vincent.bichat@epitech.eu"
copyright:           "2025 Let us cook once more"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/vincbct34/Glados-On-Top#readme>

dependencies:
- base >= 4.7 && < 5
- parser-combinators
- hspec-discover
- megaparsec
- hspec
- text
- containers
- mtl
- stm

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
  - parser-combinators

executables:
  Glados-On-Top-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Glados-On-Top

tests:
  Glados-On-Top-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Glados-On-Top
